-- Run after the hardening migration. Every temporary change is rolled back.

begin;

do $test$
declare
  function_name text;
begin
  foreach function_name in array array[
    'public.get_deck_stats(uuid)',
    'public.get_language_pair_name(text,text)',
    'public.reset_learning_profile()',
    'public.update_learning_profile(jsonb)',
    'public.update_updated_at_column()'
  ]
  loop
    if (select p.prosecdef from pg_proc p where p.oid = function_name::regprocedure) then
      raise exception '% must use SECURITY INVOKER', function_name;
    end if;

    if not coalesce((
      select p.proconfig @> array['search_path=""']
      from pg_proc p
      where p.oid = function_name::regprocedure
    ), false) then
      raise exception '% must use an empty search_path', function_name;
    end if;

    if has_function_privilege('anon', function_name, 'EXECUTE') then
      raise exception 'anon must not execute %', function_name;
    end if;
  end loop;

  if has_function_privilege('authenticated', 'public.handle_new_user()', 'EXECUTE') then
    raise exception 'authenticated must not directly execute handle_new_user()';
  end if;

  if has_function_privilege('authenticated', 'public.handle_updated_at()', 'EXECUTE') then
    raise exception 'authenticated must not directly execute handle_updated_at()';
  end if;

  if has_function_privilege('authenticated', 'public.update_updated_at_column()', 'EXECUTE') then
    raise exception 'authenticated must not directly execute update_updated_at_column()';
  end if;
end;
$test$;

select set_config(
  'request.jwt.claim.sub',
  '00000000-0000-0000-0000-000000000001',
  true
);
set local role authenticated;

do $test$
begin
  perform public.get_deck_stats('00000000-0000-0000-0000-000000000002'::uuid);
  perform public.update_learning_profile('{}'::jsonb);
  perform public.reset_learning_profile();
end;
$test$;

reset role;

create table public.__rls_probe (id bigint generated by default as identity primary key);

do $test$
begin
  if not (
    select c.relrowsecurity
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = '__rls_probe'
  ) then
    raise exception 'RLS was not enabled automatically on public.__rls_probe';
  end if;

  if has_table_privilege('anon', 'public.__rls_probe', 'SELECT')
     or has_table_privilege('authenticated', 'public.__rls_probe', 'SELECT')
     or has_table_privilege('anon', 'public.__rls_probe', 'TRUNCATE')
     or has_table_privilege('authenticated', 'public.__rls_probe', 'TRUNCATE') then
    raise exception 'New public tables must not inherit Data API privileges';
  end if;
end;
$test$;

rollback;
